FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip setuptools wheel \
    && pip install --default-timeout=120 --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "-u", "-m", "workers.worker"]